version: '3'

services:
  drupalserver:
    image: drupal
    ports: 
      - "80:8080"
    volumes:
      - ./drupal-data:/var/www/drupal
    depends_on:
      - mydb

  dbserver:
    image: postgres
    volumes:
      - .db-date:/var/db/postgres
    environment: 
      - POSTGRES_PASSWORD=juaneselmejor

